export const builtinVisualNodeDefinitions = [
  {
    type: "distribution.multi",
    label: "布局分布",
    variants: [
      "single",
      "linear",
      "grid",
      "boxMatrix",
      "sphereSurface",
      "circle",
      "concentricRings",
      "star",
    ],
    adapter: "DistributionNodeAdapter",
    updatePolicy: "onDirty",
    outputType: "TransformBuffer",
  },
  {
    type: "motionCurve.multi",
    label: "运动规律",
    variants: [
      "sine",
      "pulse",
      "saw",
      "ramp",
      "triangle",
      "noise",
      "spring",
      "collPulse",
      "constant",
    ],
    adapter: "MotionCurveNodeAdapter",
    updatePolicy: "perFrame",
    outputType: "ScalarSignal",
    params: [
      "variant",
      "frequency",
      "amplitude",
      "offset",
      "phase",
      "bipolar",

      "dutyCycle",
      "pulseCount",

      "constantValue",

      "seed",
      "noiseSmoothness",

      "springDecay",
      "springOscillations",
      "springLoop",
    ],
  },
  {
    type: "motion.multi",
    label: "基础运动",
    variants: ["rotate", "bounce", "translate"],
    adapter: "MotionNodeAdapter",
    updatePolicy: "perFrame",
    inputTypes: {
      transforms: "TransformBuffer",
      curve: "ScalarSignal?",
    },
    outputType: "TransformBuffer",
    params: [
      "variant",
      "speed",
      "amplitude",
      "frequency",
      "axis",
      "direction",
      "distance",
      "curveInfluence",
      "curveUsage",
      "angleRange",
    ],
  },
  {
    type: "particleMotion.multi",
    label: "粒子运动",
    variants: [
      "constantDirection",
      "randomWalk",
      "noise",
      "curlNoise",
      "vortex",
      "orbit",
      "attract",
      "repel",
      "flock",
      "wave",
      "turbulence",
    ],
    adapter: "ParticleMotionNodeAdapter",
    updatePolicy: "perFrame",
    inputTypes: {
      particles: "TransformBuffer|ParticleStateBuffer",
      curve: "ScalarSignal?",
    },
    outputType: "ParticleStateBuffer",
    params: [
      "variant",
      "speed",
      "strength",
      "drag",
      "maxSpeed",
      "curveInfluence",
      "curveTarget",
      "seed",
    ],
  },
  {
    type: "renderer.particles",
    label: "粒子渲染",
    variants: ["auto", "points", "instanced"],
    adapter: "ParticleRendererNodeAdapter",
    updatePolicy: "perFrame",
    inputTypes: {
      particles: "ParticleStateBuffer",
      geometry: "BufferGeometry?",
      material: "Material?",
    },
    outputType: "Object3D",
    params: [
      "renderMode",
      "shape",
      "color",
      "opacity",
      "size",
      "sizeAttenuation",
      "depthWrite",
      "depthTest",
      "orientToVelocity",
      "frustumCulled",
    ],
  },
] as const;

export const previewCreativeInspectorDefinition = {
  type: "system.previewOutput",
  label: "预览输出",
  tabs: [
    {
      id: "content",
      label: "内容",
      sections: [
        "source",
        "layout",
        "baseMotion",
        "motionCurve",
        "particleMotion",
        "renderer",
        "material",
        "lighting",
      ],
    },
    { id: "camera", label: "摄像机" },
    { id: "path", label: "路径" },
    { id: "visual", label: "画面" },
    { id: "export", label: "导出" },
  ],
} as const;
